- name: systemctl daemonreload
  systemd:
    daemon_reload: true

- name: restart zeitwork
  systemd:
    name: zeitwork
    state: restarted

- name: reload nftables
  systemd:
    name: nftables
    state: reloaded

- name: netplan apply
  command: netplan apply
  async: 30
  poll: 1